### ISSUE TITLE
Documentation: Installation hints

### ISSUE THREAD

**Issue by sneumann** [runtastic/terraform-provider-opennebula#12]
Hi, for a non-TF hardcore developer, who might have an existing configuration 
for a deployment on, say, OpenStack, it is not straight forward 
how to proceed: How is the plugin installed/activated ? 
There should be a link to e.g. the big picture at https://www.runtastic.com/blog/en/terraform-for-infrastructure-automation/ and installation instructions at 
https://www.terraform.io/docs/configuration/providers.html#third-party-plugins
and a hint where to get `terraform-provider-<NAME>_vX.Y.Z`
Also, some hint of supported TF versions would be great. 
Yours, Steffen

**Comment by sneumann** [comment]
I got the installation working with the hints from
https://github.com/dmacvicar/terraform-provider-libvirt#building-from-source

**Comment by al-lac** [comment]
Please use the [official OpenNebula Terraform provider](https://github.com/OpenNebula/terraform-provider-opennebula) for the updated and actively maintained version
