### ISSUE TITLE
netrpc: connect: no such file or directory

### ISSUE THREAD

**Issue by sneumann** [runtastic/terraform-provider-opennebula#13]
Hi again, 

when running `terraform plan` on the demo `terraform.tf` mentioned in the README, I get
```
Error asking for user input: 1 error(s) occurred:
* provider.opennebula: dial unix /tmp/plugin909097880|netrpc: connect: no such file or directory
```
This seems to be similar to the issue reported in https://github.com/russellcardullo/terraform-provider-pingdom/issues/12 . I am not skilled enough to understand the solution. Is there a combination of terraform + provider-opennebula known to work that I should try ? I am currently on a rather old'ish `Terraform v0.9.4`. Yours, Steffen

**Comment by al-lac** [comment]
Please use the [official OpenNebula Terraform provider](https://github.com/OpenNebula/terraform-provider-opennebula) for the updated and actively maintained version
