### ISSUE TITLE
Fail to compile provider with error: undefined: os.Executable

### ISSUE THREAD

**Issue by seandheath** [runtastic/terraform-provider-opennebula#5]
Good Afternoon, I'm trying to compile this provider to test it and when I type `go build -o terraform-provider-opennebula` I get the following output:

```
# github.com/hashicorp/terraform/vendor/github.com/posener/complete/cmd/install
../github.com/hashicorp/terraform/vendor/github.com/posener/complete/cmd/install/install.go:75: undefined: os.Executable
```

Any tips you have would be welcome.

`go version go1.7.4 linux/amd64`

**Comment by akurz** [comment]
Hi, 

first tip: use at least go 1.8, this is the version we are using.
