### ISSUE TITLE
Error adding vnet

### ISSUE THREAD

**Issue by denniskribl** [runtastic/terraform-provider-opennebula#6]
Hey,

I tried creating a vnet with following configuration:
```
resource "opennebula_vnet" "test" { 
  name = "test"
  description = "test"
  permissions = "600"
  bridge = "virbr0"
  ip_start = "192.168.122.200"
  ip_size = 10
}
```

tf is asking to confirm my plan before applying anything like usual, but after confirmation I'm getting following error:

```
Error: Error applying plan:
1 error(s) occurred:
* opennebula_vnet.test: 1 error(s) occurred:
* opennebula_vnet.test: [one.vn.allocate] Parse error: syntax error, unexpected VARIABLE, expecting EQUAL or EQUAL_EMPTY at line 3, columns 20:2
```

any ideas? maybe wrong mapping? I'm using OpenNebula 5.4.1
template and vm resources are working fine :)

thx in advance and thx for this nice provider :)

cheers,

**Comment by denniskribl** [comment]
nevermind I was using the description field wrong.
a look into `var testAccVnetConfigBasic` at `resource_vnet_test.go` revealed how it has to be used. Maybe add it to some kind of documentation, otherwise the issue can be closed. 

Greetings from :de:  :wave:

**Comment by akurz** [comment]
Hi ... yeah, true ... the documentation has to be improved. We see what we can do to improve that in the mid term.

thx & cheers,
Andreas
