### ISSUE TITLE
Is this repository still active?

### ISSUE THREAD

**Issue by Smurk** [runtastic/terraform-provider-opennebula#8]
Hi and sorry for opening this as issue, but I could not think of better way to contact you via GitHub.

Is someone still working on this project?
Will someone work on it in the future?

Thanks for your answers,
Jiri

**Comment by akurz** [comment]
Hi Jiri,

we use this terraform provider heavily in our environment. For our use-case the currently supported features are fine and we only add new features if we need them in our environment. So there will be active work on this if we need new features or we (or someone else) find bugs. Of course we accept pull request from the community.

Best regards,
Andreas

**Comment by jaypif** [comment]
Hello,

I am also really intersted in such tool.  That is why I post my comment here.

However, for several month now, Official GO binding are maintained in OpenNebula, do you think you will use them in the future ?
Whih Terraform version are you using ? Just to know if your module can work with latest version or not. 
If it is not the case, do you plan to update the project to work with last Terraform version.

Thank you

Best regard

Jean-Philippe

**Comment by akurz** [comment]
Hi Jean-Philippe,

we are using this provider internally on a very regular base with Terraform 0.10.8. As it is working as expected with our OpenNebula 5.4.x installation there are no plans for now to refactor the provider to use the OpenNebula Go bindings. But of course we are open to pull requests .... and this might change if we see problems after OpenNebula updates ....

Regarding the Terraform version we will very likely make sure the provider is working with Terraform 0.12.x and beyond.

Best regards,
Andreas

**Comment by jaypif** [comment]
Hi Andreas,

Thank you for your reply. 
I am thinking about adding more XML RPC in the terraform module. Especially image management as this one is missing in your version. 
I am also trying to use official Go binding to concise code. For some calls it is also require to add bindings in the official repository, so it will be a long process. 
I will test this module internally before doing a merge request to be sure it works as expected.

Best Regards.

Jean-Philippe

**Comment by cmelanson** [comment]
Hi @jp-ig1 ,

You should check out my fork https://github.com/blackberry/terraform-provider-opennebula, it's got improved image support among other things.

Corey

**Comment by jaypif** [comment]
Hi @cmelanson,

I didn't see that Blackberry also developed a recent version of what Runtastic did.
Thank you for sharing this project.

As Official Go bindings are now part of Opennebula project. and to avoid doing pull request on 2 projects, I think the ease way to have a Terraform provider for OpenNebula and using Go bindings maintained on OpenNebula is to have the Terraform provider as part of OpenNebula project.
Then it will be easy to use Goca (OCA in GO). What do you think ? Do you think it is possible to proceed in this way ? I read on OpenNebula Forum https://forum.opennebula.org/t/opennebula-devops-tools-integration/5317/12?u=jpfoures there are open to study a feature request in that way.
Do you think you can open such feature request on  github.com/OpenNebula/one ?
And to conclude They talk about your project on a Blog post today, It looks like a greenlight :).

Thank you 

Jean-Philippe
